### ISSUE TITLE
Core APIs leave for user to define

### ISSUE THREAD

**Issue by SchrodingerZhu** [chuigda/Project-CL#4]
- Arch related
  - arch_pause
  - arch_prefetch
  - arch_get_tls
  - atomic (function or macro)
  
- OS related
  - os_alloc
  - os_dealloc
  - os_set_tls
  - os_futex_wait
  - os_futex_wake
  - os_clone
  - os_write
  - os_read
 
- Proposal
  - asynchronisation (like os io_uring facilities, we can then write an executor for it)?
  - synchronisation (mutex, for example, std version provides a wrapper around pthread; no-std version provide a wrapper around raw futex)?

**Comment by chuigda** [comment]
By this time, `alloc` and `free` functions are made in the following way (see `src/alloc.c`):
- If `PROJECT_CL_ALLOC_USE_EXTERNAL` is defined, then these functions will not be provided within our library. Instead, our library will expect these functions to be linked in when it gets used in some project.
- Otherwise, if `PROJECT_CL_ALLOC_INCLUDE_IMPL` is defined, then try looking for a `alloc_impl.h`
- Otherwise, if `PROJECT_CL_ALLOC_USE_LIBC` is defined, just forward API calls to libc
- Otherwise, if `PROJECT_CL_ALLOC_USE_VALLOC` is defined, use a [valloc](https://github.com/CousinZe/valloc) alike imlementation. This might be useful for some MCU platforms.
- Otherwise, report error (via both santiy checks in `src/defs.c` AND `#error` directives in `src/alloc.c`)

I think this method can be shipped easily for other OS-related core APIs.

**Comment by chuigda** [comment]
As the final decision has been made, I'll close this.
