### ISSUE TITLE
possible "bug"

### ISSUE THREAD

**Issue by SchrodingerZhu** [chuigda/Project-CL#7]
currently, the vector should have problem with
```
push_back( vec_front( ) )
```

when a growing happens

**Comment by ICEYSELF** [comment]
Yes this is a bug, so we change the API of `vec_front` to make this impossible to happen:
```c
void CCFN(vec_front)(void *buffer);
```

**Comment by SchrodingerZhu** [comment]
According to our later discussion, this will be treated as UB for now. 

@ICEYSELF add a wontfix label or just close this?

**Comment by chuigda** [comment]
It seems that this would happen again due to our recent change. Let's take a very detailed view of this.

**Comment by chuigda** [comment]
The bug should been have fixed by the following changes in recent commit:
- `cc_vec_push` always firstly copy data to new buffer, then release the old one.
- `cc_vec_insert` always use `memmove` when no reallocation required, and does the same way as `cc_vec_push` on reallocation.

@SchrodingerZhu Have a check.

**Comment by SchrodingerZhu** [comment]
I think so.
